Projeveritabanıdeneme/Models/EntityFramework/Öğrenci.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Öğrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Öğrenci()
        {
            this.Akademik_Ders_Öğrenci = new HashSet<Akademik_Ders_Öğrenci>();
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int Öğrenci_Id { get; set; }
        public Nullable<int> Kullanıcı_Id { get; set; }
        public Nullable<int> Uzmanlık_Id { get; set; }
        public Nullable<int> Danışman_Id { get; set; }
        public string Öğrenci_Ad { get; set; }
        public string Öğrenci_Soyad { get; set; }
        public Nullable<System.DateTime> Öğrenci_Doğum_Tarihi { get; set; }
        public string Öğrenci_Doğum_Yeri { get; set; }
        public string Öğrenci_Uyruğu { get; set; }
        public Nullable<float> Öğrenci_DUS_Puanı { get; set; }
        public Nullable<System.DateTime> Uzmanlık_Eğitimi_Başlama_Tarihi { get; set; }
        public Nullable<System.DateTime> Uzmanlık_Eğitimi_Tamamlama_Tarihi { get; set; }
        public Nullable<int> Psf_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Akademik_Ders_Öğrenci> Akademik_Ders_Öğrenci { get; set; }
        public virtual Danışman Danışman { get; set; }
        public virtual Kullanıcı Kullanıcı { get; set; }
        public virtual Uzmanlık_Alanı Uzmanlık_Alanı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}

Projeveritabanıdeneme/Controllers/ÖğrenciController.cs
using Projeveritabanıdeneme.Models.EntityFramework;
using Projeveritabanıdeneme.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeveritabanıdeneme.Controllers
{
    [Authorize]
    public class ÖğrenciController : Controller
    {
        proje1Entities db = new proje1Entities();

        // GET: Öğrenci
        public ActionResult Index()
        {
            var model=db.Akademik_Ders_Öğrenci.ToList();
            return View(model);
        }
        [HttpPost]
        public ActionResult Kaydet3(Akademik_Ders_Öğrenci ders)
        {

         
                db.Akademik_Ders_Öğrenci.Add(ders);

           

            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DersKayıt()
        {
            var model = new DanismanUzmanlıkController()
            {
                Öğrenci=db.Öğrenci.ToList(),
                Akademikders = db.Akademik_Ders.ToList()

            };
            return View("DersKayıt", model);
        }
      
    }
}

Projeveritabanıdeneme/Views/Öğrenci/DersKayıt.cshtml
@model Projeveritabanıdeneme.ViewModels.DanismanUzmanlıkController

@{
    ViewBag.Title = "DersKayıt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container mt-3">
    
    <h2>Akademik Ders Ders</h2>

    @using (Html.BeginForm("Kaydet3", "Öğrenci", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Akademik_Ders_Öğrenci.Öğrenci.Öğrenci_Id)
            @Html.TextBoxFor(m => m.Akademik_Ders_Öğrenci.Öğrenci_Id, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Akademik_Ders_Öğrenci.Akademik_Ders_Id)
            @Html.DropDownListFor(m => m.Akademik_Ders_Öğrenci.Akademik_Ders_Id, new SelectList(Model.Akademikders, "Akademik_Ders_Id", "Ders_Tanımı"), "Ders Seçiniz", new { @class = "form-control" })
        </div>
      
        @Html.HiddenFor(m => m.Akademik_Ders_Öğrenci.Akademik_Ders_Öğrenci_Id);

        <button type="submit" class="btn btn-primary">Kaydet</button>
    }

</div>

Projeveritabanıdeneme/Views/Öğrenci/Index.cshtml
@using Projeveritabanıdeneme.Models.EntityFramework
@model List<Akademik_Ders_Öğrenci>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-3">

    <table class="table table-bordered">
        <p align="left">
            <a class="btn btn-dark " href="/Öğrenci/DersKayıt">Yeni Ders Ekle</a>



        <thead>
            <tr>
                <th>Ders Tanımı</th>


            </tr>
        </thead>
        <tbody>
            @foreach (var ders in Model)
            {

            <tr>
                <td>@ders.Akademik_Ders_Öğrenci_Id</td>

            </tr>
            }

        </tbody>
    </table>
</div>