Projeveritabanıdeneme/Controllers/SecurityController.cs
using Projeveritabanıdeneme.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Projeveritabanıdeneme.Controllers
{
   
    public class SecurityController : Controller
    {
        proje1Entities vtys2=new proje1Entities();
        // GET: Security
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Kullanıcı kullanıcı)
        {

            var kullanıcıIn = vtys2.Kullanıcı.FirstOrDefault(x => x.Kullanıcı_Adı == kullanıcı.Kullanıcı_Adı
            && x.Parola == kullanıcı.Parola);
            if (kullanıcıIn != null)
            {
                FormsAuthentication.SetAuthCookie(kullanıcıIn.Kullanıcı_Adı, false);
                return RedirectToAction("Index2", "Admin");
            }
            else
            {
                ViewBag.Mesaj = "Geçersiz Kullanıcı Adı,Şifre veya Rol";
                return View();
            }


        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return View("Login");
        }
    }
}

Projeveritabanıdeneme/Views/Security/Login.cshtml
@model Projeveritabanıdeneme.Models.EntityFramework.Kullanıcı
@{ Layout = null; }

<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container mt-3 align-content-center" >
        <div class="container">
            <h2>Lütfen Giriş Yapınız</h2>
            @ViewBag.Mesaj
            @using (Html.BeginForm("Login", "Security", FormMethod.Post))
            {
    <div class="form-group">
        @Html.LabelFor(m => m.Kullanıcı_Adı)
        @Html.TextBoxFor(m => m.Kullanıcı_Adı, new { @class = "form-control", placeholder = "Kullanıcı Adı" })
    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Parola)
                                        @Html.PasswordFor(m => m.Parola, new { @class = "form-control", placeholder = "Şifre" })
                                    </div>

                                                    <button class="btn btn-block btn-success">Giriş Yap</button>}


        </div>
        </div>
</body>
</html>